40 - Keyboard plugins
CrankshaftForSteam/crankshaft pull request #21
Opened 2022-08-27 22:34 UTC by TheDgtl

This change allows loading plugins on the OSK in Desktop mode by adding the "keyboard" entrypoint to the Desktop list of plugin.toml.

There is quite a delay between the keyboard loading and the plugin executing, due to the full Crankshaft backend being injected, which takes a second. I wouldn't recommend using this in a plugin at the moment due to this delay, but the framework laid here should work once that delay is fixed.

There is also a small change around the Systray stuff to stop a crash when running Crankshaft via SSH directly on the steam deck (DISPLAY isn't set, so the systray icon can't be used when run this way)

2022-09-03 03:14 UTC, coolavery requested changes
Sorry about the late review, looks great! Just one minor thing

2022-09-03 19:45 UTC, TheDgtl commented on injected/src/entrypoints/keyboard.ts
> +  waitForElement(MENU_DESKTOP_SELECTORS.keyboardContainer);
Woops, no idea how I missed that, fixed!

2022-09-03 19:46 UTC, TheDgtl commented on tray/tray.go
> +	// Only enable the systray if there's a DISPLAY env variable on Linux
No worries, it's an easy thing to miss if you're not running over SSH

2022-09-14 00:20 UTC, coolavery approved these changes

2022-09-14 00:29 UTC, coolavery commented
Sorry about the late merge, thanks!

> To git.sr.ht:~avery/crankshaft
>    e2d3a60..95e8c34  main -> main

2022-09-14 00:29 UTC, closed without merging